version: "3"
services:
  api:
    container_name: api
    build:
      context: ./backend
    volumes:
      - db:/db
    ports:
      - 8000:8000
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
volumes:
  db: